### PR TITLE
kohya-ss/sd-scripts example didn't seem to work. Updated README and added a Dataset config to streamline running train_network.py

### PR DESCRIPTION
**Pull request by asutermo**
When using the provided examples with sd-scripts, the 'train_data_dir' was always ignored and images weren't found. Added dataset config to rectify the issue and updated the command in the README

### CODE REVIEW

**Comment by KohakuBlueleaf** [comment]
Thx for providing the informations!

BTW, will the "resolution" settings in dataset_config affect the ARB settings in training_config?

**Comment by KohakuBlueleaf** [comment]
BTW, can you open a new PR to dev branch?

**Comment by asutermo** [comment]
> BTW, can you open a new PR to dev branch?

Sure! I'll do that tomorrow. I'll double check the dataset resolution setting as well.

**Comment by asutermo** [comment]
Changed to dev. Looking into resolution today

**Comment by KohakuBlueleaf** [comment]
I think not matter what "resolution" is, this PR still ok though.
Since if user want to get more detail they should just goto kohya-ss/sd-scripts

**Comment by asutermo** [comment]
Thanks for merging! Was away on holiday!

**Pull request merged**
