### PR TITLE
Added load from weights option

### PR DESCRIPTION
**Pull request by neonsecret**
To continue training from weights
Also ignore the linter indentation

### CODE REVIEW

**Comment by KohakuBlueleaf** [comment]
You should check all the lora_name and which keys they have to determine the algorithm
since in the future LyCORIS will support to train different algo for different modules (already have progress in dev)

And also, will suggest you to make pr to dev branch

**Comment by adhikjoshi** [comment]
> You should check all the lora_name and which keys they have to determine the algorithm

If you can help in finding algo from keys? maybe a util function to find algo would be helpful.

**Comment by KohakuBlueleaf** [comment]
> > You should check all the lora_name and which keys they have to determine the algorithm
> 
> If you can help in finding algo from keys? maybe a util function to find algo would be helpful.

You can refer to the merge function in utils.py
It should have an function to load algo/weight from sd for single block

**Comment by KohakuBlueleaf** [comment]
Since I already implement this into dev version in more generalized way
I will close this pr

**Pull request closed without merging**
